<?php

namespace app\admin\controller;

use app\model\UserModel;
use think\App;
use think\Db;
use think\Exception;
use think\Request;

class Agent extends Base
{
    public function __construct(Request $app)
    {
        parent::__construct($app);
        $this->model = UserModel::class;
    }


    public function queryWhere()
    {
        if(!empty($this->param['user_name'])){
            $this->param[] = ['user.user_name','like','%'.$this->param['user_name'].'%'];
        }
        return parent::queryWhere();
    }


    public function beforeAdd($param)
    {
        if(!empty($param['password'])){
            $param['password'] = md5($param['password']);
        }
        return parent::beforeAdd($param); // TODO: Change the autogenerated stub
    }


    /**
     * 查看坐席开通记录
     */
    public function agentRecordView(){
        $param = $this->request->param();
        $all_arr=[];
        $adminInfo = session('adminInfo');
        $user_id = $adminInfo['id'];
        $host = Db::table('user_host')->where('user_id',$user_id)->order('host desc')->select();
        if($this->request->isAjax()) {
            foreach ($host as $v) {
                $config = $this->getDataBaseConfig('', $v);
                $host = explode('.',$v['host']);
                $list = Db::connect($config)->table('mx_user')->field('name,full_name,FROM_UNIXTIME(reg_time,"%Y-%m-%d %H:%i:%s") reg_time,"'.$host[0].'" as host')->select();
                if (is_array($list)) {
                    $all_arr = array_merge($list, $all_arr);
                }
            }
            $limit = $param['limit'];
            $page = $param['page'];
            $offset = $limit*($page - 1);
            $count = count($all_arr);
            $all_arr = array_slice($all_arr,$offset,$limit);
            return $this->success($all_arr,'success',0,['count' => $count]);
        }

    }


}