<?php

namespace app\admin\controller;

use app\common\exception\BaseException;
use app\common\mongo\MongoDb;
use app\model\AdminModel;
use app\model\HelpModel;
use app\model\UserModel;
use think\App;
use think\Db;
use think\Exception;
use think\Request;

class Help extends Base
{
    public function __construct(Request $app)
    {
        parent::__construct($app);
        $this->model = HelpModel::class;
    }


    public function queryWhere()
    {
        if(!empty($this->param['user_name'])){
            $this->param[] = ['user.user_name','like','%'.$this->param['user_name'].'%'];
        }
        return parent::queryWhere();
    }


    public function beforeAdd($param)
    {
        return parent::beforeAdd($param); // TODO: Change the autogenerated stub
    }



    /**
     * 公共上传
     * @return \think\response\Json
     */
    public function upload()
    {
        $file = $this->request->file('file');
        if($file){
            $move = ROOT_PATH.'/public/static/upload/';
            $res = $file->move($move,true,false);
            $data = [
                'src' => '/public/static/upload/'.$res->getSaveName() ,
            ];
            if($res){
                return $this->success($data,'上传成功',0);
            } else{
                return $this->error([],'上传失败');
            }
        }else{
            return $this->error([],'上传失败');
        }
    }


    /**
     * 查看坐席开通记录
     */
    public function agentRecordView(){
        $param = $this->request->param();
        $all_arr=[];
        if($this->request->isAjax()) {
            // 获取所有的账号坐席
            $host = Db::table('user_host')->where('user_id',$param['id'])->order('host desc')->select();
            foreach ($host as $v) {
                $config = $this->getDataBaseConfig('', $v);
                $host = explode('.',$v['host']);
                $list = Db::connect($config)->table('mx_user')->field('name,full_name,FROM_UNIXTIME(reg_time,"%Y-%m-%d %H:%i:%s") reg_time,"'.$host[0].'" as host')->select();
                if (is_array($list)) {
                    $all_arr = array_merge($list, $all_arr);
                }
            }
            $limit = $param['limit'];
            $page = $param['page'];
            $offset = $limit*($page - 1);
            $count = count($all_arr);
            $all_arr = array_slice($all_arr,$offset,$limit);
            return $this->success($all_arr,'success',0,['count' => $count]);
        }else{
            $this->assign('list',$all_arr);
            $this->assign('id',$param['id']);
            $this->assign('type',$param['type']);
            $this->assign('url','/admin/user/agentRecordView?id='.$param['id']);
            return $this->fetch('user/agentRecordView');
        }

    }


}
