<?php

namespace app\admin\controller;


use app\model\HistoryModel;
use think\Db;
use think\Exception;
use think\Request;

class History extends Base
{
    public function __construct(Request $app)
    {
        parent::__construct($app);
        $this->model = HistoryModel::class;
    }


    public function index()
    {
        if($this->role_id == 1){
            $host = Db::connect(\config('data_base_3'))->table('ipdata')->where('status',1)->where('type',1)->select();
        }else{
            $ipdata = Db::table('user_host')->select();
            $ipdata = array_column($ipdata,'ipdata_id','ipdata_id');
            $host = Db::connect(\config('data_base_3'))->table('ipdata')->where('status',1)->where('type',1)->whereIn('id',$ipdata)->select();
        }
        $this->assign('host',$host);
        return parent::index(); // TODO: Change the autogenerated stub
    }


    public function indexAjax()
    {
        if(!empty($this->param['ipdata_id'])){
            $config = $this->getDataBaseConfig($this->param['ipdata_id']);
        }

        $this->queryWhere();

        if(!empty($this->param) && count($this->param) > 2){
            $model = (new $this->model);
            $model->db_config = $config;
            list($count,$data) = $model->indexAjax($this->param);
            return $this->success($this->afterIndexAjax($data),'',0,['count' => $count]);
        }else{
            return $this->success([],'',0,['count' => 0]);
        }
    }



    public function queryWhere()
    {
        if(!empty($this->param['start_time']) && !empty($this->param['end_time'])){
            $this->param[] = ['created_time','between',strtotime($this->param['start_time']).','. strtotime($this->param['end_time']) ];
        }
        return parent::queryWhere();
    }




}