<?php

namespace app\admin\controller;

use app\common\exception\BaseException;
use app\common\mongo\MongoDb;
use app\model\AdminModel;
use app\model\UserModel;
use think\App;
use think\Db;
use think\Exception;
use think\Request;

class User extends Base
{
    public function __construct(Request $app)
    {
        parent::__construct($app);
        $this->model = UserModel::class;
    }


    public function queryWhere()
    {
        if(!empty($this->param['user_name'])){
            $this->param[] = ['user.user_name','like','%'.$this->param['user_name'].'%'];
        }
        return parent::queryWhere();
    }


    public function beforeAdd($param)
    {
        if(!empty($param['password'])){
            $param['password'] = md5($param['password']);
        }
        return parent::beforeAdd($param); // TODO: Change the autogenerated stub
    }


    /**
     * 修改密码和充值
     * @return mixed|\think\response\Json
     * @throws Exception
     * @throws \think\exception\PDOException
     */
    public function change_pass()
    {
        $param = $this->request->param();
        if($this->request->isAjax()){
            $res = true;
            if(!empty($param['password'])){
                $res = Db::table('user')->where('id',$param['id'])->update([
                    'updated_at' => time(),
                    'password' => md5($param['password'])
                ]);
            }
            if(isset($param['price'])){
                if($param['price'] <= 0){
                    return $this->error([],'充值数量必须大于0');
                }
                $res = Db::table('user')->where('id',$param['id'])->setInc('price',$param['price']);
            }
            if($res){
                return $this->success();
            }else{
                return $this->error();
            }
        }else{
            $this->assign('id',$param['id']);
            $this->assign('type',$param['type']);
            $this->assign('url','/admin/user/change_pass');
            return $this->fetch('user/change_pass');
        }
    }

    /**
     * 查看坐席总数
     * @return \think\response\Json
     * @throws Exception
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     */
    public function look_set()
    {
        $param = $this->request->param();
        $host = Db::table('user_host')->where('user_id',$param['id'])->select();
        if(empty($host)) return $this->success(['num' => 0]);
        $number = 0;
        foreach ($host as $v){
            $config = $this->getDataBaseConfig('',$v);
            $number += Db::connect($config)->table('mx_user')->count();
        }

        return $this->success(['num' => $number]);
    }



    /**
     * 公共上传
     * @return \think\response\Json
     */
    public function upload()
    {
        $file = $this->request->file('file');
        if($file){
            $move = ROOT_PATH.'/public/static/upload/';
            $res = $file->move($move,true,false);
            $data = [
                'src' => '/public/static/upload/'.$res->getSaveName() ,
            ];
            if($res){
                return $this->success($data,'上传成功',0);
            } else{
                return $this->error([],'上传失败');
            }
        }else{
            return $this->error([],'上传失败');
        }
    }


}